catcollector_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cats/', views.cats_index, name='index'),
    path('cats/<int:cat_id>/', views.cat_detail, name='detail'),
    path('cats/create/', views.CatCreate.as_view(), name='cats_create'),
    path('cats/<int:pk>/update/', views.CatUpdate.as_view(), name='cats_update'),
    path('cats/<int:pk>/delete/', views.CatDelete.as_view(), name='cats_delete'),
    # Feeding URL
    path('cats/<int:pk>/add_feeding/', views.add_feeding, name='add_feeding'),
    # Toy association URL
    path('cats/<int:pk>/assoc_toy/<int:toy_pk>/', views.assoc_toy, name='assoc_toy'),
    path('cats/<int:pk>/assoc_delete/<int:toy_pk>', views.assoc_delete, name='assoc_delete'),
    ## TOY URLS ##
    path('toys/', views.ToyList.as_view(), name='toys_index'),
    path('toys/<int:pk>/', views.ToyDetail.as_view(), name='toys_detail'),
    path('toys/create/', views.ToyCreate.as_view(), name='toys_create'),
    path('toys/<int:pk>/update/', views.ToyUpdate.as_view(), name='toys_update'),
    path('toys/<int:pk>/delete/', views.ToyDelete.as_view(), name='toys_delete'),
    # User Auth URLS
    path('accounts/signup/', views.signup, name='signup'),

]

catcollector_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('catcollector_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

catcollector_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# choices for cat's feeding schedule
MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('toys_detail', kwargs={'pk': self.id})


# Create your models here.
class Cat(models.Model):
    name = models.CharField(max_length=100)
    breed = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    toys = models.ManyToManyField(Toy)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'cat_id': self.id})
    

class Feeding(models.Model):
    date = models.DateField('feeding Date')
    meal = models.CharField(
        max_length=1,
        choices=MEALS,
        default=MEALS[0][0]
    )
    # on delete they will remove all Feeding instances related to the deleted cat
    cat = models.ForeignKey(Cat, on_delete=models.CASCADE)

    def __str__(self):
        # get_Field_display() returns a human readable value for the field
        return f"{self.get_meal_display()} on {self.date}"
    
class Meta:
    ordering = ['-date']

catcollector_app/forms.py
from django.forms import ModelForm
from .models import Feeding 

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ['date', 'meal']

catcollector_app/views.py
from django.shortcuts import render, redirect
# from django.http import HttpResponse
from django.views.generic import CreateView, UpdateView, DeleteView, ListView, DetailView
from .models import Cat, Toy
from .forms import FeedingForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Add this cats list below the imports
# cats = [
#   {'name': 'Lolo', 'breed': 'tabby', 'description': 'furry little demon', 'age': 3},
#   {'name': 'Sachi', 'breed': 'calico', 'description': 'gentle and loving', 'age': 2},
# ]

# Create your views here.
def home(request):
    # res.send('hello') in express
    # return HttpResponse('hello')
    return render(request, 'cats/home.html')

def about(request):
    return render(request, 'cats/about.html')

@login_required
def cats_index(request):
    cats = Cat.objects.filter(user=request.user)
    # passing data extremely similar to EJS
    return render(request, 'cats/index.html', {
        'cats': cats
    })

@login_required
def cat_detail(request, cat_id):
    cat = Cat.objects.get(id=cat_id)
    toys = Toy
    # Get the toys the cat doesn't have
    id_list = cat.toys.all()
    toys_cat_doesnt_have = Toy.objects.exclude(id__in=id_list)
    # making an instance of the FeedingForm class
    feeding_form = FeedingForm()
    return render(request, 'cats/detail.html', {
        'cat': cat, 
        'feeding_form': FeedingForm,
        'toys': toys_cat_doesnt_have
    })

@login_required
def add_feeding(request, pk):
    # create a ModelForm instance with POST data
    # this is like req.body in express
    form = FeedingForm(request.POST)
    # validate the form
    if form.is_valid():
        # dont save the form until it has our cat_id assigned
        new_feeding = form.save(commit=False)
        # date, meal, cat --> cat_id is django magic
        new_feeding.cat_id = pk
        new_feeding.save()
    return redirect('detail', cat_id=pk)

@login_required
def assoc_toy(request, pk, toy_pk):
  # Note that you can pass a toy's id instead of the whole toy object
  Cat.objects.get(id=pk).toys.add(toy_pk)
  return redirect('detail', cat_id=pk)

@login_required
def assoc_delete(request, pk, toy_pk):
  Cat.objects.get(id=pk).toys.remove(toy_pk)
  return redirect('detail', cat_id=pk)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in via code
            login(request, user)
            return redirect('index')
    else:
        error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)


class CatCreate(LoginRequiredMixin, CreateView):
    model = Cat
    fields = ['name', 'breed', 'description', 'age']

    # This inherited method is called when a valid cat form is submitted
    def form_valid(self, form):
        # form instance assigning 'user' field to the logged in user 'self.request.user'        
        form.instance.user = self.request.user
        # let the CreateView do its job as usual
        return super().form_valid(form)

class CatUpdate(LoginRequiredMixin, UpdateView):
    model = Cat
    fields = ['breed', 'description', 'age']

class CatDelete(LoginRequiredMixin, DeleteView):
    model = Cat
    success_url = '/cats/'

class ToyList(LoginRequiredMixin, ListView):
    model = Toy

class ToyDetail(LoginRequiredMixin, DetailView):
    model = Toy

class ToyCreate(LoginRequiredMixin, CreateView):
    model = Toy
    fields = '__all__'

class ToyUpdate(LoginRequiredMixin, UpdateView):
  model = Toy
  fields = ['name', 'color']

class ToyDelete(LoginRequiredMixin, DeleteView):
  model = Toy
  success_url = '/toys'

catcollector_app/templates/catcollector_app/cat_confirm_delete.html
{% extends 'cats/base.html' %}

{% block content %}
  <h1>Delete Cat</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' cat.id %}">Cancel</a>
  </form>
{% endblock %}

catcollector_app/templates/catcollector_app/cat_form.html
{% extends 'cats/base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Cat</h1>
{% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="POST">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

catcollector_app/templates/catcollector_app/toy_confirm_delete.html
{% extends 'cats/base.html' %}

{% block content %}
  <h1>Delete Toy</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'toys_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

catcollector_app/templates/catcollector_app/toy_detail.html
{% extends 'cats/base.html' %}
{% block content %}

<h1>Toy Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ toy.name }}</span>
        <p>Color: {{ toy.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'toys_update' toy.id %}">Edit</a>
        <a href="{% url 'toys_delete' toy.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

catcollector_app/templates/catcollector_app/toy_form.html
{% extends 'cats/base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Toy</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

catcollector_app/templates/catcollector_app/toy_list.html
{% extends 'cats/base.html' %}
{% block content %}

<h1>Toy List</h1>

{% for toy in toy_list %}
  <a href="{% url 'toys_detail' toy.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ toy.name }}</span>
            <p>Color: {{ toy.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

catcollector_app/templates/cats/about.html
{% extends 'cats/base.html' %}
{% block content %}

<h1>About the Cat Collector</h1>
<hr>
<p>Hire the Cat Collector!</p>
{% endblock %}

catcollector_app/templates/cats/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Cat Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Cat Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'toys_create' %}">Add a Toy</a></li>
            <li><a href="{% url 'toys_index' %}">View All Toys</a></li>
            <li><a href="{% url 'cats_create' %}">Add a Cat</a></li>
            <li><a href="{% url 'index' %}">View All My Cats</a></li>
            <!-- <li><a href="{% url 'logout' %}">Log Out</a></li>     -->
            <!-- Django 5.0+ requires a POST request for logout -->
            <li>
              <form method="POST" action="{% url 'logout' %}">
                {% csrf_token %}
                <input type="submit" class="btn" value="Log Out"/>
              </form>
            </li>
          {% else %}
            <li><a href="{% url 'signup' %}">Sign UP</a></li>
            <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
      </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
     All Rights Reserved, &copy; {% now "Y" %} Cat Collector
  </footer>
</body>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
    });
  });

  const selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>
</html>

catcollector_app/templates/cats/detail.html
{% extends 'cats/base.html' %}
{% block content %}

<h1>Cat Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ cat.name }}</span>
        <p>Breed: {{ cat.breed }}</p>
        <p>Description: {{ cat.description|linebreaks }}</p>
        {% if cat.age > 0 %}
          <p>Age: {{ cat.age }}</p>
        {% else %}
          <p>Age: Kitten</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'cats_update' cat.id %}">Edit</a>
        <a href="{% url 'cats_delete' cat.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_feeding' cat.id %}" method="POST">
      {% csrf_token %}
      <!-- Render the inputs -->
      {{ feeding_form.as_p }}
      <input type="submit" class="btn" value="Add Feeding">
    </form>  
    <table class="striped">
      <thead>
        <tr><th>Date</th><th>Meal</th></tr>
      </thead>
      <tbody>
        {% for feeding in cat.feeding_set.all %}
          <tr>
            <td>{{feeding.date}}</td>
            <td>{{feeding.get_meal_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ cat.name }}'s Toys</h3>
    {% if cat.toys.count %}
      {% for toy in cat.toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_delete' cat.id toy.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn red">Remove</button>
            </form>
          </div>        
        </div>
      {% endfor %}
    {% else %}
      <h5>No Toys 😿</h5>
    {% endif %}
  </div>
  <!-- Available toys will come after this line -->
  <div class="col s6">
    <h3>Available Toys</h3>
    {% if toys.count %}
      {% for toy in toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_toy' cat.id toy.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{cat.name}} Already Has All Toys Available</h5>
    {% endif %}
  </div>
</div>
{% endblock %}

catcollector_app/templates/cats/home.html
{% extends 'cats/base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

catcollector_app/templates/cats/index.html
{% extends 'cats/base.html' %}
{% block content %}

<h1>Cat List</h1>

{% for cat in cats %}
  <div class="card">
    <a href="{% url 'detail' cat.id %}">
      <div class="card-content">
        <span class="card-title">{{ cat.name }}</span>
        <p>Breed: {{ cat.breed }}</p>
        <p>Description: {{ cat.description | linebreaks}}</p>
        {% if cat.age > 0 %}
          <p>Age: {{ cat.age }}</p>
        {% else %}
          <p>Age: Kitten</p>
        {% endif %}
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}